language: android

before_script:
   - mkdir -p "$ANDROID_HOME/licenses"
   - cp .android-licenses/* "$ANDROID_HOME/licenses/"

script:
  - ./gradlew build

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

before_deploy:
    - git tag -d latest
    # Set up git user name and tag this commit
    - git config --local user.name "TRAVIS-CI"
    - git config --local user.email "ariedov@gmail.com"
    - git tag "latest"
deploy:
    provider: releases
    api-key: GITHUB_API_KEY
    file: "app/build/outputs/apk/release/release.apk"
    skip_cleanup: true
